version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      gradle-wrapper:
        patterns: ["gradle-wrapper"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
